### ISSUE TITLE
Add Geotrellis

### ISSUE THREAD

**Issue by ALPSMAC** [lauris/awesome-scala#307]
Geotrellis is an awesome Scala library for geospatial processing: http://geotrellis.io/

I was surprised to not find it on this aggregation list.

**Comment by angelcervera** [comment]
So maybe is good to have a new section related to GIS:
 - [Geotrellis](http://geotrellis.io/)
 - [Osm4scala](https://github.com/angelcervera/osm4scala)


What do you think?

**Comment by SethTisue** [comment]
can we just close old issues like this that should have been pull requests?

**Comment by ALPSMAC** [comment]
I thought I did put up a PR for this actually.  I guess I forgot to close
the issue.  My apologies - please feel free to close it.

**Comment by longcao** [comment]
@SethTisue I wouldn't mind! I've just been merging PRs as they come pretty generously (almost blindly).

Otherwise, some other ideas I had:

* Get rid of the hourglass characters in entries (I forget what this is)
* Fix up the `metadata.py` script or figure out something else altogether, I do like the idea of keeping stars by repos and bolding repos that have > 500 stars
* Cull or fix invalid links
* Audit the table of contents and maybe reorder where things should be
* Re-alphasort within sections as they've gone out of order (or figure out a better way to list entries if there is, but I don't think I would want to sort by stars and bias towards the projects that already have a lot)

I don't know how the process would go in terms of adding contributors but I think @lauris would need to do it. Or perhaps this repo would be better off moved to a single repo org?

**Comment by SethTisue** [comment]
@lauris would you be willing to anoint additional maintainers with merge powers in this repo, or even better, with admin powers, so we could ourselves anoint additional maintainers?

I humbly nominate myself; I'm a member of the Scala team at Lightbend.

**Comment by lauris** [comment]
Sure thing, I will look into this tomorrow.

**Comment by longcao** [comment]
Not that I have much of an excuse for not grooming the repo better, but more hands would definitely help.

+1 from me to add @SethTisue to repo admin, I vouch for his trustworthiness here. I also wouldn't mind repo admin, but up to you.

**Comment by lauris** [comment]
@longcao I appreciate your efforts here, you have done a lot during the past years. 

I will add the necessary permissions.

**Comment by SethTisue** [comment]
@lauris thank you!

@longcao I've opened issues for some of your suggestions

I also:

* merged (or requested changes) on all open pull requests
* closed open issues that were merely requesting additions, inviting a pull request instead
* made sure all the remaining open issues at least appear to make sense
* labeled issues as "help wanted"
* made a "maintainers wanted" issue: https://github.com/lauris/awesome-scala/issues/431
