### ISSUE TITLE
merge with https://github.com/awesome-scala/awesome-scala ?

### ISSUE THREAD

**Issue by SethTisue** [lauris/awesome-scala#435]
@joshlemer alerted me to the existence of https://github.com/awesome-scala/awesome-scala

Josh what's best here, should that one go forward as the "official" one, or should the changes be merged here, or what?

**Comment by joshlemer** [comment]
I think that awesome-scala/awesome-scala is a better namespace, (no offence to lauris, and thank you to them for starting this one), see also github.com/awesome-scala/not-yet-awesome-scala. But we probably don't want to lose all the SEO and links around the internet to this repo.   
So either "ownership" of this repo could be given to awesome-scala org (which would forward traffic from here to there), or we could merge those travis-ci changes into this repo and just accept the lauris namespace.

**Comment by SethTisue** [comment]
@lauris wdyt?

**Comment by lauris** [comment]
I'd prefer to not to move it. 

There is no such thing as "official" list. Anybody can start their own with whatever name they choose and in my opinion namespace/name is the least important thing.

**Comment by dwijnand** [comment]
That's true, but there's value in combining multiple efforts into a single list and that list being hosted under an officially URL, for instance just to remember.

Is there anything, in particular, you're concerned about in transferring the repo?

**Comment by lauris** [comment]
I agree that there is value in combining efforts - I'm very open to accepting maintainers and welcome new contributions to this repo. However I don't think that this repo should be moved because it's already the most popular Scala list and has a long history. In my opinion changing name doesn't offer any significant benefit and could only create confusion. 

Take a look at great and popular awesome lists:
https://github.com/sindresorhus/awesome-nodejs
https://github.com/razum2um/awesome-clojure
https://github.com/enaqx/awesome-react
https://github.com/sorrycc/awesome-javascript

They are under the original author's username and there is no problem with that.

**Comment by joshlemer** [comment]
Yep that's totally fine
