### ISSUE TITLE
listings should be alphabetized

### ISSUE THREAD

**Issue by softprops** [lauris/awesome-scala#81]
the current ordering of listings for each category seems arbitrary. perhaps this should be part of the contribution guidelines.

**Comment by longcao** [comment]
Dredging this discussion back up since I'm planning to fix up/reorganize the list a bit soon - my preference would be for alphasort since sorting by anything else can be daunting to maintain over time if manual, not to mention that not all entries are GitHub projects.

If there's a clever script out there to accomplish popularity or recent updates sort then maybe...

**Comment by non** [comment]
My proposal -- alphabetical names but maybe with star counts and/or last-active dates included, possibly with bolding based on a threshold.

I think it would be easy to create a script that hits the GH API and updates the Markdown document, which could be run periodically.

Too weird an idea?

**Comment by non** [comment]
(Although when I think about it -- I'm not sure baking in a *requirement* that projects must use Github is a great idea.)

**Comment by longcao** [comment]
@non those sound within the realm of possibility, combining alphasort and star counts/last-active might give us best of both worlds. Maybe inserting in buttons from something like https://ghbtns.com/ could also be nice.

No requirement on GitHub - if it isn't on GH then don't have a star count or last active by the entry since your proposal is also organized by alpha anyways.

**Comment by non** [comment]
Hey so I created this: https://gist.github.com/non/bc0cac3053b4cb532b09

I am a terrible webdev, so I don't know how to set up OAuth2. Does anyone have any experience with this?

**Comment by longcao** [comment]
Closed by #139.
